name: rap-mb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pybind11
  - numpy
  - scipy
  - matplotlib
  - sphinx
  - cmake
  - jupyter
  - notebook
  - sundials
  - mkl-devel
  - mkl
  - tbb-devel
  - onemkl-sycl-blas
  - onemkl-sycl-lapack
  - dpcpp-cpp-rt 
  - dpcpp_linux-64
  - intel-cmplr-lib-rt 
  - intel-cmplr-lic-rt 
  - intel-fortran-rt 
  - intel-openmp
